add_newline = false

format = """
╭──$username@$hostname - $directory $git_branch$git_status
╰─$character
"""

[username]
show_always = true
format = "[$user]($style)"
style_user = "bold #89b4fa"

[hostname]
ssh_only = false
format = "[$hostname]($style)"
style = "bold #a6adc8"

[directory]
format = "[$path]($style)"
style = "bold #94e2d5"
truncation_length = 1
truncate_to_repo = false

[git_branch]
symbol = " "
style = "bold #a6e3a1"
format = "on [$symbol$branch]($style) "

[git_status]
style = "bold #f2cdcd"
format = "([$all_status$ahead_behind]($style) )"
conflicted = "="
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"

[character]
success_symbol = "[](#94e2d5)"
error_symbol = "[](#f38ba8)"
