monitor = eDP-1, 1920x1080, 0x0, 1
monitor = HDMI-A-1, 1920x1080, 0x0, 1, mirror, eDP-1

source = ~/.config/hypr/binds.conf
source = ~/.config/hypr/appearance.conf

exec-once = waybar & hyprpaper & 
exec-once = wl-paste --watch cliphist store &
exec-once = cliphist wipe

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 

    touchpad {
        natural_scroll = false
    }
}

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
